const cardDeck = [
    // spades
        {suit: 'spade', rank: 'ace', value: 11, hasBeenPlayed: false, src: './img/cards/spade-a.png', aceValueChanged: false},
        {suit: 'spade', rank: '2', value: 2, hasBeenPlayed: false, src: './img/cards/spade-2.png'},
        {suit: 'spade', rank: '3', value: 3, hasBeenPlayed: false, src: './img/cards/spade-3.png'},
        {suit: 'spade', rank: '4', value: 4, hasBeenPlayed: false, src: './img/cards/spade-4.png'},
        {suit: 'spade', rank: '5', value: 5, hasBeenPlayed: false, src: './img/cards/spade-5.png'},
        {suit: 'spade', rank: '6', value: 6, hasBeenPlayed: false, src: './img/cards/spade-6.png'},
        {suit: 'spade', rank: '7', value: 7, hasBeenPlayed: false, src: './img/cards/spade-7.png'},
        {suit: 'spade', rank: '8', value: 8, hasBeenPlayed: false, src: './img/cards/spade-8.png'},
        {suit: 'spade', rank: '9', value: 9, hasBeenPlayed: false, src: './img/cards/spade-9.png'},
        {suit: 'spade', rank: '10', value: 10, hasBeenPlayed: false, src: './img/cards/spade-10.png'},
        {suit: 'spade', rank: 'jack', value: 10, hasBeenPlayed: false, src: './img/cards/spade-j.png'},
        {suit: 'spade', rank: 'queen', value: 10, hasBeenPlayed: false, src: './img/cards/spade-q.png'},
        {suit: 'spade', rank: 'king', value: 10, hasBeenPlayed: false, src: './img/cards/spade-k.png'},
    // hearts
        {suit: 'heart', rank: 'ace', value: 11, hasBeenPlayed: false, src: './img/cards/heart-a.png', aceValueChanged: false},
        {suit: 'heart', rank: '2', value: 2, hasBeenPlayed: false, src: './img/cards/heart-2.png'},
        {suit: 'heart', rank: '3', value: 3, hasBeenPlayed: false, src: './img/cards/heart-3.png'},
        {suit: 'heart', rank: '4', value: 4, hasBeenPlayed: false, src: './img/cards/heart-4.png'},
        {suit: 'heart', rank: '5', value: 5, hasBeenPlayed: false, src: './img/cards/heart-5.png'},
        {suit: 'heart', rank: '6', value: 6, hasBeenPlayed: false, src: './img/cards/heart-6.png'},
        {suit: 'heart', rank: '7', value: 7, hasBeenPlayed: false, src: './img/cards/heart-7.png'},
        {suit: 'heart', rank: '8', value: 8, hasBeenPlayed: false, src: './img/cards/heart-8.png'},
        {suit: 'heart', rank: '9', value: 9, hasBeenPlayed: false, src: './img/cards/heart-9.png'},
        {suit: 'heart', rank: '10', value: 10, hasBeenPlayed: false, src: './img/cards/heart-10.png'},
        {suit: 'heart', rank: 'jack', value: 10, hasBeenPlayed: false, src: './img/cards/heart-j.png'},
        {suit: 'heart', rank: 'queen', value: 10, hasBeenPlayed: false, src: './img/cards/heart-q.png'},
        {suit: 'heart', rank: 'king', value: 10, hasBeenPlayed: false, src: './img/cards/heart-k.png'},
    // clubs
        {suit: 'club', rank: 'ace', value: 11, hasBeenPlayed: false, src: './img/cards/club-a.png', aceValueChanged: false},
        {suit: 'club', rank: '2', value: 2, hasBeenPlayed: false, src: './img/cards/club-2.png'},
        {suit: 'club', rank: '3', value: 3, hasBeenPlayed: false, src: './img/cards/club-3.png'},
        {suit: 'club', rank: '4', value: 4, hasBeenPlayed: false, src: './img/cards/club-4.png'},
        {suit: 'club', rank: '5', value: 5, hasBeenPlayed: false, src: './img/cards/club-5.png'},
        {suit: 'club', rank: '6', value: 6, hasBeenPlayed: false, src: './img/cards/club-6.png'},
        {suit: 'club', rank: '7', value: 7, hasBeenPlayed: false, src: './img/cards/club-7.png'},
        {suit: 'club', rank: '8', value: 8, hasBeenPlayed: false, src: './img/cards/club-8.png'},
        {suit: 'club', rank: '9', value: 9, hasBeenPlayed: false, src: './img/cards/club-9.png'},
        {suit: 'club', rank: '10', value: 10, hasBeenPlayed: false, src: './img/cards/club-10.png'},
        {suit: 'club', rank: 'jack', value: 10, hasBeenPlayed: false, src: './img/cards/club-j.png'},
        {suit: 'club', rank: 'queen', value: 10, hasBeenPlayed: false, src: './img/cards/club-q.png'},
        {suit: 'club', rank: 'king', value: 10, hasBeenPlayed: false, src: './img/cards/club-k.png'},
    // diamonds
        {suit: 'diamond', rank: 'ace', value: 11, hasBeenPlayed: false, src: './img/cards/diamond-a.png', aceValueChanged: false},
        {suit: 'diamond', rank: '2', value: 2, hasBeenPlayed: false, src: './img/cards/diamond-2.png'},
        {suit: 'diamond', rank: '3', value: 3, hasBeenPlayed: false, src: './img/cards/diamond-3.png'},
        {suit: 'diamond', rank: '4', value: 4, hasBeenPlayed: false, src: './img/cards/diamond-4.png'},
        {suit: 'diamond', rank: '5', value: 5, hasBeenPlayed: false, src: './img/cards/diamond-5.png'},
        {suit: 'diamond', rank: '6', value: 6, hasBeenPlayed: false, src: './img/cards/diamond-6.png'},
        {suit: 'diamond', rank: '7', value: 7, hasBeenPlayed: false, src: './img/cards/diamond-7.png'},
        {suit: 'diamond', rank: '8', value: 8, hasBeenPlayed: false, src: './img/cards/diamond-8.png'},
        {suit: 'diamond', rank: '9', value: 9, hasBeenPlayed: false, src: './img/cards/diamond-9.png'},
        {suit: 'diamond', rank: '10', value: 10, hasBeenPlayed: false, src: './img/cards/diamond-10.png'},
        {suit: 'diamond', rank: 'jack', value: 10, hasBeenPlayed: false, src: './img/cards/diamond-j.png'},
        {suit: 'diamond', rank: 'queen', value: 10, hasBeenPlayed: false, src: './img/cards/diamond-q.png'},
        {suit: 'diamond', rank: 'king', value: 10, hasBeenPlayed: false, src: './img/cards/diamond-k.png'}
]