const cardDeck = [
    // spades
        {suit: 'spade', rank: 'ace', value: 11, hasBeenPlayed: false, src: './img/spade-ace.png', aceValueChanged: false},
        {suit: 'spade', rank: '2', value: 2, hasBeenPlayed: false, src: './img/spade-2.png'},
        {suit: 'spade', rank: '3', value: 3, hasBeenPlayed: false, src: './img/spade-3.png'},
        {suit: 'spade', rank: '4', value: 4, hasBeenPlayed: false, src: './img/spade-4.png'},
        {suit: 'spade', rank: '5', value: 5, hasBeenPlayed: false, src: './img/spade-5.png'},
        {suit: 'spade', rank: '6', value: 6, hasBeenPlayed: false, src: './img/spade-6.png'},
        {suit: 'spade', rank: '7', value: 7, hasBeenPlayed: false, src: './img/spade-7.png'},
        {suit: 'spade', rank: '8', value: 8, hasBeenPlayed: false, src: './img/spade-8.png'},
        {suit: 'spade', rank: '9', value: 9, hasBeenPlayed: false, src: './img/spade-9.png'},
        {suit: 'spade', rank: '10', value: 10, hasBeenPlayed: false, src: './img/spade-10.png'},
        {suit: 'spade', rank: 'jack', value: 10, hasBeenPlayed: false, src: './img/spade-jack.png'},
        {suit: 'spade', rank: 'queen', value: 10, hasBeenPlayed: false, src: './img/spade-queen.png'},
        {suit: 'spade', rank: 'king', value: 10, hasBeenPlayed: false, src: './img/spade-king.png'},
    // hearts
        {suit: 'heart', rank: 'ace', value: 11, hasBeenPlayed: false, src: './img/heart-ace.png', aceValueChanged: false},
        {suit: 'heart', rank: '2', value: 2, hasBeenPlayed: false, src: './img/heart-2.png'},
        {suit: 'heart', rank: '3', value: 3, hasBeenPlayed: false, src: './img/heart-3.png'},
        {suit: 'heart', rank: '4', value: 4, hasBeenPlayed: false, src: './img/heart-4.png'},
        {suit: 'heart', rank: '5', value: 5, hasBeenPlayed: false, src: './img/heart-5.png'},
        {suit: 'heart', rank: '6', value: 6, hasBeenPlayed: false, src: './img/heart-6.png'},
        {suit: 'heart', rank: '7', value: 7, hasBeenPlayed: false, src: './img/heart-7.png'},
        {suit: 'heart', rank: '8', value: 8, hasBeenPlayed: false, src: './img/heart-8.png'},
        {suit: 'heart', rank: '9', value: 9, hasBeenPlayed: false, src: './img/heart-9.png'},
        {suit: 'heart', rank: '10', value: 10, hasBeenPlayed: false, src: './img/heart-10.png'},
        {suit: 'heart', rank: 'jack', value: 10, hasBeenPlayed: false, src: './img/heart-jack.png'},
        {suit: 'heart', rank: 'queen', value: 10, hasBeenPlayed: false, src: './img/heart-queen.png'},
        {suit: 'heart', rank: 'king', value: 10, hasBeenPlayed: false, src: './img/heart-king.png'},
    // clubs
        {suit: 'club', rank: 'ace', value: 11, hasBeenPlayed: false, src: './img/club-ace.png', aceValueChanged: false},
        {suit: 'club', rank: '2', value: 2, hasBeenPlayed: false, src: './img/club-2.png'},
        {suit: 'club', rank: '3', value: 3, hasBeenPlayed: false, src: './img/club-3.png'},
        {suit: 'club', rank: '4', value: 4, hasBeenPlayed: false, src: './img/club-4.png'},
        {suit: 'club', rank: '5', value: 5, hasBeenPlayed: false, src: './img/club-5.png'},
        {suit: 'club', rank: '6', value: 6, hasBeenPlayed: false, src: './img/club-6.png'},
        {suit: 'club', rank: '7', value: 7, hasBeenPlayed: false, src: './img/club-7.png'},
        {suit: 'club', rank: '8', value: 8, hasBeenPlayed: false, src: './img/club-8.png'},
        {suit: 'club', rank: '9', value: 9, hasBeenPlayed: false, src: './img/club-9.png'},
        {suit: 'club', rank: '10', value: 10, hasBeenPlayed: false, src: './img/club-10.png'},
        {suit: 'club', rank: 'jack', value: 10, hasBeenPlayed: false, src: './img/club-jack.png'},
        {suit: 'club', rank: 'queen', value: 10, hasBeenPlayed: false, src: './img/club-queen.png'},
        {suit: 'club', rank: 'king', value: 10, hasBeenPlayed: false, src: './img/club-king.png'},
    // diamonds
        {suit: 'diamond', rank: 'ace', value: 11, hasBeenPlayed: false, src: './img/diamond-ace.png', aceValueChanged: false},
        {suit: 'diamond', rank: '2', value: 2, hasBeenPlayed: false, src: './img/diamond-2.png'},
        {suit: 'diamond', rank: '3', value: 3, hasBeenPlayed: false, src: './img/diamond-3.png'},
        {suit: 'diamond', rank: '4', value: 4, hasBeenPlayed: false, src: './img/diamond-4.png'},
        {suit: 'diamond', rank: '5', value: 5, hasBeenPlayed: false, src: './img/diamond-5.png'},
        {suit: 'diamond', rank: '6', value: 6, hasBeenPlayed: false, src: './img/diamond-6.png'},
        {suit: 'diamond', rank: '7', value: 7, hasBeenPlayed: false, src: './img/diamond-7.png'},
        {suit: 'diamond', rank: '8', value: 8, hasBeenPlayed: false, src: './img/diamond-8.png'},
        {suit: 'diamond', rank: '9', value: 9, hasBeenPlayed: false, src: './img/diamond-9.png'},
        {suit: 'diamond', rank: '10', value: 10, hasBeenPlayed: false, src: './img/diamond-10.png'},
        {suit: 'diamond', rank: 'jack', value: 10, hasBeenPlayed: false, src: './img/diamond-jack.png'},
        {suit: 'diamond', rank: 'queen', value: 10, hasBeenPlayed: false, src: './img/diamond-queen.png'},
        {suit: 'diamond', rank: 'king', value: 10, hasBeenPlayed: false, src: './img/diamond-king.png'}
]